### ISSUE TITLE
What am I doing wrong here?

### ISSUE THREAD

**Issue by Simpuhl** [JannikBirn/palworld-host-save-fix#1]
![image](https://github.com/JannikBirn/palworld-host-save-fix/assets/262571/04dd87bb-f397-4e4d-bddd-01a5af67809b)

**Comment by JannikBirn** [comment]
> If you utilized the tool from xNul, the setup process will differ slightly. Initially, you will require [palworld-save-tools](https://github.com/cheahjs/palworld-save-tools) instead of uesave-rs. This will be automatically downloaded if you clone this repository; otherwise, you need to download palworld-save-tools separately and place it inside the lib/palworld-save-tools folder. The command now requires one less argument; you no longer need to provide the <uesave.exe> path due to the previous step.
You need to download the [palworld-save-tools](https://github.com/cheahjs/palworld-save-tools)  as well and place it inside the folder "lib/palworld-save-tools". This will automatically happen if you clone the repo using git. Otherwise you need to download and place it manually there. 
I'll try to find a more convenient way to so this.

**Comment by Simpuhl** [comment]
By the way, I don't think it automatically pulls palworld-save-tools

I cloned like this for example:
git clone https://github.com/JannikBirn/palworld-host-save-fix.git %USERPROFILE%\GitHub\palworld-host-save-fix

**Comment by Simpuhl** [comment]
ahh I think I know what I did wrong, clearly in the screenshot I am working off the "zip" file lol. Hold up

**Comment by JannikBirn** [comment]
Here is how you clone a repository: https://docs.github.com/de/repositories/creating-and-managing-repositories/cloning-a-repository

**Comment by Simpuhl** [comment]
> > If you utilized the tool from xNul, the setup process will differ slightly. Initially, you will require [palworld-save-tools](https://github.com/cheahjs/palworld-save-tools) instead of uesave-rs. This will be automatically downloaded if you clone this repository; otherwise, you need to download palworld-save-tools separately and place it inside the lib/palworld-save-tools folder. The command now requires one less argument; you no longer need to provide the <uesave.exe> path due to the previous step.
> 
> You need to download the [palworld-save-tools](https://github.com/cheahjs/palworld-save-tools) as well and place it inside the folder "lib/palworld-save-tools". This will automatically happen if you clone the repo using git. Otherwise you need to download and place it manually there. I'll try to find a more convenient way to so this.

Doesn't that just clone it to my own tho? That's why I always do it from cmd line like this:

git clone https://github.com/JannikBirn/palworld-host-save-fix.git %USERPROFILE%\GitHub\palworld-host-save-fix

**Comment by Simpuhl** [comment]
I got it to run properly now but it came back with this error:

![image](https://github.com/JannikBirn/palworld-host-save-fix/assets/262571/f2d98079-16c4-48f3-971f-8f693b86e4a5)

**Comment by MaxEffort94** [comment]
> I got it to run properly now but it came back with this error:
> 
> Edit: Full Screenshot
> 
> ![image](https://private-user-images.githubusercontent.com/262571/300230773-8054e028-7c16-4770-ba47-b68362a79dd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MDk4NDgsIm5iZiI6MTcwNjQwOTU0OCwicGF0aCI6Ii8yNjI1NzEvMzAwMjMwNzczLTgwNTRlMDI4LTdjMTYtNDc3MC1iYTQ3LWI2ODM2MmE3OWRkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOFQwMjM5MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNTQ5YmU0NmIwNzRkNTZlZGVhZDZmYzgzMzEzMDkxNWRhNDhlMDU4NzVkZTExNWFlOWYxZWNiOWIyYjBjMzU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wbCjvDg2Vv-s66h38OTMIu5EO9vKOIJQFZwyMjeD-FE)
> 
> Ignore the first line, I can C:\ twice

getting the same error 

![image](https://github.com/JannikBirn/palworld-host-save-fix/assets/73554906/be5730ed-61c2-42d8-81d4-dac43b54fdac)

**Comment by JannikBirn** [comment]
Just pushed a fix. Please fetch and pull the newest commit. It should work now.

**Comment by MaxEffort94** [comment]
> Just pushed a fix. Please fetch and pull the newest commit. It should work now.

okay, this all worked, kept character, can access base, pals are working, same for my 2 friends. however, a very strange bug has orrcured, when i send a pal out, it will attack my friends and same the other way. we do not play as part of a guild, we play seperatly (3 of us).

**Comment by JannikBirn** [comment]
> > Just pushed a fix. Please fetch and pull the newest commit. It should work now.
> 
> okay, this all worked, kept character, can access base, pals are working, same for my 2 friends. however, a very strange bug has orrcured, when i send a pal out, it will attack my friends and same the other way. we do not play as part of a guild, we play seperatly (3 of us).

That sounds very strange. Do the pals actually deal damage? Do you have the pvp flag in the server settings enabled? I thought that pvp wasn't a thing for now. 
The thing is there are some other cases that I found where the player guide appears but if I replaced those I either kepped the pickup bug or lost all pals. But it might relate to this issue. 
I'll taste this tomorrow with one of my friends and see if we got the same problem. Stay tuned!

**Comment by MaxEffort94** [comment]
> > > Just pushed a fix. Please fetch and pull the newest commit. It should work now.
> > 
> > 
> > okay, this all worked, kept character, can access base, pals are working, same for my 2 friends. however, a very strange bug has orrcured, when i send a pal out, it will attack my friends and same the other way. we do not play as part of a guild, we play seperatly (3 of us).
> 
> That sounds very strange. Do the pals actually deal damage? Do you have the pvp flag in the server settings enabled? I thought that pvp wasn't a thing for now. The thing is there are some other cases that I found where the player guide appears but if I replaced those I either kepped the pickup bug or lost all pals. But it might relate to this issue. I'll taste this tomorrow with one of my friends and see if we got the same problem. Stay tuned!

pals deal damage yes. i tried to get him to  join my guild and leave, but for some reason i ended up taking ownership of his guild. also the left click bug is still present. however, this is massive progress, at least i can host a server keep everything, good work! hopefull you can sort out this hostile pal issue

**Comment by Simpuhl** [comment]
Do I just copy my playerfile back or also level.sav ?

**Comment by MaxEffort94** [comment]
> Do I just copy my playerfile back or also level.sav ?
> 
> I only did my player profile and I just get a now loading... screen.
> 
> ![image](https://private-user-images.githubusercontent.com/262571/300232516-cdd72555-f98f-44d1-ac74-d4b0c8550771.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MTI3ODEsIm5iZiI6MTcwNjQxMjQ4MSwicGF0aCI6Ii8yNjI1NzEvMzAwMjMyNTE2LWNkZDcyNTU1LWY5OGYtNDRkMS1hYzc0LWQ0YjBjODU1MDc3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOFQwMzI4MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MGE2N2IwZTBiODMxY2FmODFjOTI1ZWEzM2QxZjcxZjM3OTI4ZTIzZWJkNmJlZDlkMjNjMTcwZjkzZWY5MWZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Aw5g6WnI_BVOkT3OlYffyE-xcNnAo3Bvpxq_Zd5IP_Y)

entire save folder

**Comment by Simpuhl** [comment]
> entire save folder

I stopped server, did just the level.sav and prayer file again and its working

**Comment by Simpuhl** [comment]
You can mark this as resolved if you want. Not sure if you want to include level.sav and player.sav in the instructions to be copied back. That's all I had to do and I am good. 

I am the only person on my server so Idk if id be experiencing the bug that @MaxEffort94 is or not.

**Comment by davidckim** [comment]
> > Just pushed a fix. Please fetch and pull the newest commit. It should work now.
> 
> okay, this all worked, kept character, can access base, pals are working, same for my 2 friends. however, a very strange bug has orrcured, when i send a pal out, it will attack my friends and same the other way. we do not play as part of a guild, we play seperatly (3 of us).

We are running into this issue as well. How were you able to fix this?

We have a weird bug on our server where tamed pals will start fighting other tamed pals but they do no damage to each other. PVP is disabled too. Tried to fix for about a week now.
